[package]
name = "dcap-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
hex          = "0.4"
x509-parser  = "0.15.1"
p256         = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "p256/v0.13.2" }
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1.0"